# -------------------------------------------------------------------------------
#FILE NAME:      _______________
#DESCRIPTION:    CS 202 - Lab _
#USAGE:          ./sales_struct_v5               // Interactive mode
#COMPILER:       GNU g++ compiler on Linux
#NOTES:          Test program for structures
#Modification    History:

#Author                  Date            Version
#------------------      -----------     -----------
#Christopher Zinser      2020-..-..      v5
#-------------------------------------------------------------------------------*/



.cpp :
	g++ -o $* $*.cpp -std=c++11

matrix_math1: Matrix.cpp Matrix.h
matrix_math: Matrix.cpp Matrix.h			